replicaCount: 1

image:
  repository: "cr.yandex/crpjocodvb4840j8jqg2/gateway"
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []

nameOverride: "gateway"
fullnameOverride: "gateway"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "gateway"

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  name: http
  annotations:
    gwin.yandex.cloud/targets.type: Node

auth:
  issuerUri: "https://idp.81.26.187.28.nip.io"

env:
  - name: SERVER_PORT
    value: "8080"
  - name: SPRING_APPLICATION_NAME
    value: "gateway"
  - name: DOWNSTREAM_FLIGHTS
    value: "http://flights:8060"
  - name: DOWNSTREAM_TICKETS
    value: "http://tickets:8070"
  - name: DOWNSTREAM_PRIVILEGES
    value: "http://privileges:8050"
  - name: DOWNSTREAM_STATISTICS
    value: "http://statistics:8091"
  - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
    value: "{{ .Values.auth.issuerUri }}"

ingress:
  enabled: true
  className: "gwin-default"
  annotations:
    gwin.yandex.cloud/groupName: rsoi
    gwin.yandex.cloud/externalIPv4Address: auto
  hosts:
    - host: 81.26.187.28.nip.io
      paths:
        - path: /api/v1
          pathType: Prefix
  tls:
    - hosts:
        - 81.26.187.28.nip.io
      secretName: yc-certmgr-cert-id-fpqpgeqbp2irtdnf11it

resources: {}

livenessProbe:
  httpGet:
    path: /manage/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /manage/health
    port: http
  initialDelaySeconds: 20
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 2

nodeSelector: {}
tolerations: []
affinity: {}
