apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.postgresql.initScriptsConfigMap }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
data:
  10-create-user.sql: |
    -- Create program user for microservices
    DO
    $do$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ .Values.postgresql.applicationUser.name }}') THEN
        CREATE ROLE {{ .Values.postgresql.applicationUser.name }} WITH LOGIN PASSWORD '{{ .Values.postgresql.applicationUser.password }}';
      ELSE
        ALTER ROLE {{ .Values.postgresql.applicationUser.name }} WITH LOGIN PASSWORD '{{ .Values.postgresql.applicationUser.password }}';
      END IF;
    END
    $do$;

  db-v1.sql: |
    -- Database initialization script
    {{- range .Values.postgresql.databases }}
    CREATE DATABASE {{ . }} OWNER {{ $.Values.postgresql.applicationUser.name }};
    GRANT ALL PRIVILEGES ON DATABASE {{ . }} TO {{ $.Values.postgresql.applicationUser.name }};
    {{- end }}
