apiVersion: v1
kind: Service
metadata:
  name: {{ include "redpanda.fullname" . }}
  labels:
    {{- include "redpanda.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafka
      port: {{ .Values.service.kafkaPort }}
      targetPort: kafka
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "redpanda.selectorLabels" . | nindent 4 }}
